### ISSUE TITLE
Wrong set of properties in annotations

### ISSUE THREAD

**Issue by marcverhagen** [lappsgrid-services/edu.brandeis.cs.opennlp-web-service#6]
When running the OpenNLP POS tagger on the output of a tokenizer (I used the Vassar Stanford tokenizer: org.anc.lapps.stanford.Tokenizer:2.0.0), we get the following:

```json
{ 
  "metadata": {
    "contains":{"http://vocab.lappsgrid.org/Token#pos":{
      "producer":"edu.brandeis.cs.lappsgrid.opennlp.POSTagger:2.0.2",
      "type":"tagger:opennlp"}}},
  "annotations": [
    { "id":"pos_0","start":0,"end":1,
       "@type":"http://vocab.lappsgrid.org/Token#pos",
       "type":"http://vocab.lappsgrid.org/Token#pos",
       "label":"http://vocab.lappsgrid.org/Token#pos",
       "features":{"pos":"NN"}}]
}
```

Both `type` and `label` should probably be removed since they are a holdover from ancient days and they tend to be confusing here. While `@type` is cool because its JSON-LD angle and it being mentioned in LIF, neither `type` nor `label` have that distinction. Also note that `type` and `label` are both mentioned in http://vocab.lappsgrid.org/schema/lif-schema.json.

**Comment by keighrim** [comment]
[v2.0.3](https://github.com/lappsgrid-services/edu.brandeis.cs.opennlp-web-service/tree/v2.0.3) should fix this. It's already released and deployed on the public lapps galaxy.
